spring:
  config:
    import: env.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carrier
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: ${DDL.AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS.PASSWORD}

auth:
  base-url: ${AUTH.BASE.URL}
  client-id: ${AUTH.CLIENT.ID}
  client-secret: ${AUTH.CLIENT.SECRET}
  redirect-url: ${AUTH.REDIRECT.URL}
  scopes: ${AUTH.SCOPES}

jwt:
  access-time: ${JWT.ACCESS.TIME}
  refresh-time: ${JWT.REFRESH.TIME}
  prefix: ${JWT.PREFIX}
  header: ${JWT.HEADER}
  secret-key: ${JWT.SECRET.KEY}
